homepage: "https://github.com/clibs/clib"
language: c
primary_contact: "joseph.werle@gmail.com"
auto_ccs:
  - "Adam@adalogics.com"
  - "isty001@gmail.com"
fuzzing_engines:
  - libfuzzer
  - honggfuzz
sanitizers:
  - address
  - undefined
  - memory
main_repo: 'https://github.com/clibs/clib'
