homepage: "https://www.dovecot.org/"
language: c
primary_contact: "oss-fuzz@open-xchange.com"
auto_ccs:
    - "david@adalogics.com"
    - "p.antoine@catenacyber.fr"
    - "cmousefi@gmail.com"
    - "boschstephan@gmail.com"
    - "timo.sirainen@gmail.com"
