homepage: https://gitlab.freedesktop.org/cairo/cairo
language: c
primary_contact: security-tps@google.com
sanitizers:
  - address
  - undefined
  
view_restrictions: none
main_repo: 'https://gitlab.freedesktop.org/cairo/cairo.git'
