homepage: "https://www.clamav.net/"
language: c++
primary_contact: "clamav.fuzz@gmail.com"
auto_ccs:
    - clamav-bugs@external.cisco.com
sanitizers:
 - address
 - undefined
main_repo: 'https://github.com/Cisco-Talos/clamav-devel.git'
