homepage: "https://github.com/PJK/libcbor"
primary_contact: "me@pavelkalvoda.com"
auto_ccs:
  - alex.gaynor@gmail.com
fuzzing_engines:
  - afl
  - libfuzzer
  - honggfuzz
  - dataflow
sanitizers:
  - address
  - undefined
  - memory
  - dataflow
