homepage: "http://www.ntp.org"
primary_contact: "security@ntp.org"
auto_ccs:
  - "p.antoine@catenacyber.fr"
fuzzing_engines:
  - afl
  - libfuzzer
  - honggfuzz
  - dataflow
sanitizers:
  - address
  - memory
  - undefined
  - dataflow
