homepage: "https://www.tcpdump.org"
primary_contact: "security@tcpdump.org"
auto_ccs :
- "p.antoine@catenacyber.fr"
- "infra.station@gmail.com"
- "guy@alum.mit.edu"

sanitizers:
- address
- memory
- undefined
