homepage: "https://www.rnpgp.com/"
language: c++
primary_contact: "tse@ribose.com"
auto_ccs:
  - "tom@ritter.vg"
  - "o.nickolay@gmail.com"
  - "daniel.wyatt@gmail.com"
sanitizers:
  - address
  - undefined
fuzzing_engines:
  - libfuzzer
  - honggfuzz
  - afl