homepage: "https://github.com/protobuf-c/protobuf-c"
language: c
primary_contact: "guidovranken@gmail.com"
sanitizers:
 - address
 - memory
architectures:
 - x86_64
 - i386
main_repo: 'https://github.com/protobuf-c/protobuf-c.git'
