homepage: "https://github.com/yaml/pyyaml"
language: python
primary_contact: "pyyaml@yaml.com"
auto_ccs:
  - "david@adalogics.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
main_repo: "https://github.com/yaml/pyyaml"
