homepage: "https://github.com/SerenityOS/serenity"
language: c++
primary_contact: "kling@serenityos.org"
auto_ccs:
  - "david@adalogics.com"
  - "mail@linusgroh.de"
  - "ali.mpfard@gmail.com"
  - "luke.wilde@live.co.uk"
  - "bugaevc@serenityos.org"

# Bug reports are public by default:
view_restrictions: none
