homepage: "https://www.wolfssl.com/"
language: c++
primary_contact: "jacob@wolfssl.com"
auto_ccs:
  - "david@wolfssl.com"
  - "john@wolfssl.com"
  - "john.safranek@gmail.com"
  - "kaleb@wolfssl.com"
  - "kaleb.himes@gmail.com"
  - "levi@wolfssl.com"
  - "testing@wolfssl.com"
  - "guidovranken@gmail.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
  - dataflow
sanitizers:
  - address
  - memory:
     experimental: True
  - undefined
  - dataflow
